In [1]:
import numpy as np

1. Создайте массив arr_1 размером 3х4, все элементы которого равны 3

In [2]:
arr_1 = np.full((3, 4), 3)
print(arr_1)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


2. Создайте массив arr_2, заполненный случайными целыми числами от 0 до
9, размером 2х4.

In [7]:
arr_2 = np.random.randint(0, 11, (2, 4))
print(arr_2)

[[10  7  5  5]
 [ 8  4  7  2]]


3. Выведите на экран количество элементов в созданных массивах arr_1 и
arr_2.


In [8]:
print(arr_1.size, arr_2.size)

12 8


4. Соедините массивы arr_1 и arr_2 по нулевой оси.

In [9]:
print(np.append(arr_1, arr_2, axis=0))


[[ 3  3  3  3]
 [ 3  3  3  3]
 [ 3  3  3  3]
 [10  7  5  5]
 [ 8  4  7  2]]


5. Создайте массив arr_3 из кортежа чисел (1, 8, 6, 5, 8, 3) с помощью функции
np.array()

In [10]:
a = (1, 8, 6, 5, 8, 3)
arr_3 = np.array(a)
print(arr_3)

[1 8 6 5 8 3]


6. Умножьте каждый элемент массива arr_3 на число 3 и прибавьте к каждому
элементу 1. Результат запишите в новый массив arr_4.

In [12]:
arr_4 = arr_3 * 3 + 1
print(arr_4)

[ 4 25 19 16 25 10]


7. Преобразуйте масиив arr_3 к двумерному массиву 2х3. Результат запишите
в массив arr_5.

In [14]:
arr_5 = arr_3.reshape(2, 3)
print(arr_5)

[[1 8 6]
 [5 8 3]]


8. Определите минимальные элементы массива arr_5 вдоль первой оси.

In [17]:
print(np.min(arr_5,axis=1))

[1 3]


9. Вычислите среднее арифметическое всех элементов массива arr_5.


In [18]:
print(np.mean(arr_5))

5.166666666666667


10. Создайте массив arr_6, состоящий из квадратов чисел от 0 до 10. 

In [19]:
arr_6 = np.square(np.arange(11))
print(arr_6)

[  0   1   4   9  16  25  36  49  64  81 100]


11. Выведите каждый второй элемент массива arr_6.

In [20]:
print(arr_6[::2])

[  0   4  16  36  64 100]


12. Выведите элементы массива arr_6 в обратном порядке.

In [21]:
print(arr_6[::-1])

[100  81  64  49  36  25  16   9   4   1   0]


13. Каждому второму элементу массива arr_6 присвойте значение 2

In [22]:
arr_6[::2] = 2
print(arr_6)

[ 2  1  2  9  2 25  2 49  2 81  2]


14. Проверьте, есть ли в массиве arr_6 значение 49.

In [23]:
print(49 in arr_6)

True


15. Создайте двумерный массив А, состоящий из положительных и
отрицательных чисел. Из массива A выберите все отрицательные элементы и
запишите их в одномерный массив B.

In [25]:
A = np.random.randint(-10, 10, (3, 4))
B = A[A < 0]
print(A)
print(B)

[[-8 -3  1 -1]
 [ 3 -9 -8  7]
 [ 2 -1 -8 -3]]
[-8 -3 -1 -9 -8 -1 -8 -3]
